---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nen-app
  labels:
    app: nen-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nen-app
  template:
    metadata:
      name: nen-app
      labels:
        app: nen-app
    spec:
      containers:
        - name: nen-app
          image: n8nio/n8n:nightly
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5678
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nen-app
  namespace: n8n
spec:
  selector:
    app: nen-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nen-ingress
  namespace: n8n
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - <your-domain>
      secretName: n8n-tls-secret
  rules:
    - host: <your-domain>
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: nen-app
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
  namespace: n8n
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <your-email>
    privateKeySecretRef:
      name: letsencrypt-production-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-tls-secret
  namespace: n8n
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-cert
  namespace: n8n
spec:
  secretName: n8n-tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt-production
  commonName: <your-external-domain>
  dnsNames:
    - <your-external-domain>
---
